// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Climb struct {
	ID     int32
	Name   pgtype.Text
	Grade  pgtype.Text
	Cragid pgtype.Int4
}
