version: '3'
services:
  CragApp:
    container_name: App-container
    image: 96d4ff0c578e
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@CragDb:5432/postgres "
    ports:
      - "6969:6969"
    depends_on:
      - CragDb
  
  CragDb:
    container_name: CragDb-container
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
