-- Create tables
CREATE TABLE crag (
	Id SERIAL PRIMARY KEY, 
	Name TEXT UNIQUE, 
	Latitude DOUBLE PRECISION,
	Longitude DOUBLE PRECISION
);

CREATE TABLE climb (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(255) UNIQUE,
	Grade VARCHAR(255),
	CragID INTEGER REFERENCES crag(Id)
);

CREATE TABLE report (
	Id SERIAL PRIMARY KEY, 
	Content VARCHAR(255),
	Author VARCHAR(255),
	CragID INTEGER REFERENCES crag(Id)
);